### ISSUE TITLE
There is no files in the Release page.

### ISSUE THREAD

**Issue by darrenchwu** [stevenshizzleh/the-north-star#1]
There is no files in the Release page.
https://github.com/stevenshizzleh/gen3-pt-settings/releases

**Comment by JackONeill12** [comment]
Calm down. PT2 isn't out yet. PTM is not updated for 2.0. Give it time ;)

**Comment by stevenshizzleh** [comment]
It's coming. Updated the FAQ. We'll try to get the settings out within a week or so.

**Comment by stevenshizzleh** [comment]
Still working on it. This is all contingent on PTMagic coming out with an update as well, so that's part of the hold up.

**Comment by bsoung** [comment]
Thanks for the hard work steven and team!

**Comment by stevenshizzleh** [comment]
Still working on it guys. We're close. Unfortunately, some of the indicators in PT aren't working right and we had to find that out the hard way while developing the settings. They take time to nail down because we backtest and run the bot in test mode at the same time to see how things are performing. Hold tight -- soon!

**Comment by bsoung** [comment]
Seems like PT pushed out a fix for STOCH and some other bugs recently :)

**Comment by denniscepero** [comment]
Been checking in everyday. Can't wait to see what you got for us Mr. Sizzleh.

**Comment by stevenshizzleh** [comment]
All set!
